### ISSUE TITLE
Is there a non async version of the latest release?

### ISSUE THREAD

**Issue by sdesh** [nager/Nager.AmazonProductAdvertising#115]
This is a great library we Thank you! 

Amazon is requiring everyone to stop using PA API 4 and use PA API 5 by March 9th 2020. 

Our app uses Nager.AmazonProductAdvertising v1.2.2.

Upgrading to v2.06 does not have the sync methods. (That I can see)
By any chance are there a non async methods for this library available which utilizes PA API 5?

Thank you.

**Comment by tinohager** [comment]
No, it is not available

**Comment by sdesh** [comment]
ok, I assumed so. Thanks for the quick reply.

**Comment by hiromi3** [comment]
Hello,
Do you have any plan to develop non-async version api functions?
Because, I have been using old version of  Nager.AmazonProductAdvertising in my web sites.
I tried to use async functions of latest Nager,  but I am not able to do it yet.
So, the simplest solution is to use non-async functions.
I want to know the future plan of Nager.AmazonProductAdvertising project.
