### ISSUE TITLE
Missing SearchIndex values

### ISSUE THREAD

**Issue by Sergey-Vlasov** [nager/Nager.AmazonProductAdvertising#120]
According to https://webservices.amazon.com/paapi5/documentation/locale-reference/united-states.html#search-index it should be possible to specify for example MoviesAndTV and AmazonVideo, but these values are missing from SearchIndex https://github.com/nager/Nager.AmazonProductAdvertising/blob/master/src/Nager.AmazonProductAdvertising/Model/SearchIndex.cs

**Comment by stengnath** [comment]
Absolutely correct.
The problem is that indices are differenzt for each localization.
https://webservices.amazon.com/paapi5/documentation/locale-reference.html

I will try to bring all indizes together into one list and then I will do a pull request.
For all practical purposes  every localization have to be implemented.
